### ISSUE TITLE
ReferenceError: width is not defined

### ISSUE THREAD

**Issue by m7mdra** [flutter-clutter/svg-to-flutter-path-converter#5]
Hi

When i run the following command 

`svg-to-flutter convert Downloads/ic_mail.svg -o path.dart`

i get this error 

```js
/Users/user1/svg-to-flutter-path-converter/src/convert.js:252
  let pathData = getPathData(shapes, width, height);
                                     ^
ReferenceError: width is not defined
    at shapesToFlutterCodeConverter (/Users/user1/svg-to-flutter-path-converter/src/convert.js:252:38)
    at SvgToFlutterPathConverter.convertFromString (/Users/user1/svg-to-flutter-path-converter/src/convert.js:54:12)
    at SvgToFlutterPathConverter.convertFromFilePath (/Users/user1/svg-to-flutter-path-converter/src/convert.js:26:17)
    at Command.<anonymous> (/Users/user1/svg-to-flutter-path-converter/src/index.js:24:35)
    at Command.listener [as _actionHandler] (/Users/user1/svg-to-flutter-path-converter/node_modules/commander/lib/command.js:481:17)
    at /Users/user1/svg-to-flutter-path-converter/node_modules/commander/lib/command.js:1237:65
    at Command._chainOrCall (/Users/user1/svg-to-flutter-path-converter/node_modules/commander/lib/command.js:1153:12)
    at Command._parseCommand (/Users/user1/svg-to-flutter-path-converter/node_modules/commander/lib/command.js:1237:27)
    at Command._dispatchSubcommand (/Users/user1/svg-to-flutter-path-converter/node_modules/commander/lib/command.js:1059:25)
    at Command._parseCommand (/Users/user1/svg-to-flutter-path-converter/node_modules/commander/lib/command.js:1202:19)

Node.js v18.3.0
```
i tried with a big svg then thought size might be an issue or file included tags unknown..etc, then i tried with a smaller svg you will find it below

![email](https://user-images.githubusercontent.com/16242735/177151616-f97ce51e-6f09-45c9-9019-c83a1c0edfe0.svg)

Thanks in advance.

**Comment by flutter-clutter** [comment]
Hi @m7mdra. I fixed it in the latest commit. Can you pull and try again, please? :)

**Comment by m7mdra** [comment]
Hey @flutter-clutter, thanks for following up

its working now, 

However i tried it with different image with more details, curves, color. it produced the following error. 

```javascript

/Users/user1/svg-to-flutter-path-converter/src/convert.js:223
  return (value.match(/\d+/g)).map(function (o) {
                               ^

TypeError: Cannot read properties of null (reading 'map')
    at colorStringToObject (/Users/user1/svg-to-flutter-path-converter/src/convert.js:223:32)
    at /Users/user1/svg-to-flutter-path-converter/src/convert.js:319:17
    at Array.forEach (<anonymous>)
    at shapesToFlutterCodeConverter (/Users/user1/svg-to-flutter-path-converter/src/convert.js:254:18)
    at SvgToFlutterPathConverter.convertFromString (/Users/user1/svg-to-flutter-path-converter/src/convert.js:54:12)
    at SvgToFlutterPathConverter.convertFromFilePath (/Users/user1/svg-to-flutter-path-converter/src/convert.js:26:17)
    at Command.<anonymous> (/Users/user1/svg-to-flutter-path-converter/src/index.js:24:35)
    at Command.listener [as _actionHandler] (/Users/user1/svg-to-flutter-path-converter/node_modules/commander/lib/command.js:481:17)
    at /Users/user1/svg-to-flutter-path-converter/node_modules/commander/lib/command.js:1237:65
    at Command._chainOrCall (/Users/user1/svg-to-flutter-path-converter/node_modules/commander/lib/command.js:1153:12)

```

this is the image used.

![shape1](https://user-images.githubusercontent.com/16242735/182796748-b7f807b7-bfe1-4d0e-993b-9681943eff02.svg)


Thanks in advance.

**Comment by usman-whizpool** [comment]
hey, facing same error as above
<img width="971" alt="Screenshot 2022-09-29 at 11 41 01 AM" src="https://user-images.githubusercontent.com/5094671/192957856-63fee91e-5379-4e12-a2a6-ab2f0868f182.png">

**Comment by eokdev** [comment]
> hey, facing same error as above <img alt="Screenshot 2022-09-29 at 11 41 01 AM" width="971" src="https://user-images.githubusercontent.com/5094671/192957856-63fee91e-5379-4e12-a2a6-ab2f0868f182.png">
